### ISSUE TITLE
File Searching Slow

### ISSUE THREAD

**Issue by iamrecursion** [AlexBieg/obsidian-better-command-palette#1]
I love the idea of this plugin! Unfortunately, I tried out the file searcher mode and found it to be unusably slow compared to the inbuilt (cmd+O) file searcher. Do you have any plans for performance improvements?

**Comment by AlexBieg** [comment]
Thanks for trying it out! Regarding performance, the speed issues make a lot of sense in hindsight. I'm still fairly new to obsidian and have a relatively small number of files. I don't think some performance improvements would be too difficult to accomplish. I'll just need to figure out the system that `cmd+O` uses and adopt that approach. I'll make this the next thing I work on

**Comment by AlexBieg** [comment]
I think I have a fix out for this. Testing locally with 10,000 files I was definitely able to see some slowness. From what I could tell it was mostly rendering-time related. So I've added a new setting letting you limit the number of suggestions that are shown. At least for me, this fixed any slowdowns. Let me know if it worked for you!

**Comment by iamrecursion** [comment]
> I'll just need to figure out the system that `cmd+O` uses and adopt that approach. I'll make this the next thing I work on

From prior discussions with Licat, that dialog's filtering is implemented in C compiled to WASM, due to the fact that Licat couldn't get the performance to be good enough in JS alone.

That said, this is a big improvement already! My vault is ~18k files, and while I'm still seeing some hitches when filtering both commands and files this is great! Thank you so much - I'm excited to use this!

**Comment by AlexBieg** [comment]
> that dialog's filtering is implemented in C compiled to WASM

Oh, that's super interesting. I've never worked with WASM before so I'll need to do some reading, but that seems like a viable approach. 

Glad my simple fix improved stuff! This still isn't at the point where I would consider this resolved, so I'll keep this open and keep trying to improve it when I can.

**Comment by iamrecursion** [comment]
> Oh, that's super interesting. I've never worked with WASM before so I'll need to do some reading, but that seems like a viable approach.

If you do consider WASM I'd look into Rust instead of C. It has a _far_ better story around compilation and integration with JS. That said, I'm not sure that plugins can load WASM blobs on iOS. There might be some signing issues so it's worth testing with something trivial first. Another thing to keep in mind is that there's fairly significant marshalling overhead between JS and WASM, so it may not be a win here purely for filtering.

**Comment by AlexBieg** [comment]
@iamrecursion I was hoping I could lean on you for some testing. I just pushed a branch that uses the MetadataCache to grab file paths. It seems to be pretty effective for me, but I don't have the most realistic file structures (one folder with 20,000 files). If you have the bandwidth, would you be willing to pull down the test branch and give it a shot?

Branch: `issue-1-use-cache-files`

**Comment by iamrecursion** [comment]
This does seem a touch better, but there's still the hitching I was noticing beforehand. Unfortunately the performance trace isn't all that informative due to garbled names in Obsidian's source, but here are a few observations:

- `updateSuggestions` seems to dominate on every keypress (with `getSuggestions` dominating that call).
- It seems like the filtering is done in the render thread. Is this a limitation of the plugin interface (I think dataview uses web workers for example)? I know that the main open dialog does the filtering out of the render thread, so sometimes the list takes time to update but the typing never hitches.

Attached is a profile (zipped because GH doesn't accept JSON) of me typing something into the file dialog in the plugin. I hope this helps!

[Filtering.json.zip](https://github.com/AlexBieg/obsidian-better-command-palette/files/7947441/Filtering.json.zip)

**Comment by iamrecursion** [comment]
I should note that the performance hitching I'm seeing now happens when searching both commands _and_ files. The file searching itself seems much better now.

**Comment by AlexBieg** [comment]
@iamrecursion I've just released a new version of the plugin that uses web workers while fuzzy searching. It moves all of the slow functions to a new thread. Hopefully, you should no longer see stuttering when typing into the search box. If this fixes your issues, I'll close out this card. If not, I'll leave it open, but will be taking a break from this particular avenue of work. If you are anyone else feels like taking a stab at more performance improvements I'm more than happy to review PRs 😄

**Comment by iamrecursion** [comment]
This does seem to have made it absolutely blazingly fast! Thank you so much! Unfortunately I'm seeing an issue where the command palette itself is empty of commands. I do, unfortunately, have an issue that I've reported in #14.

**Comment by iamrecursion** [comment]
Thank you so much for your hard work on this! It's absolutely brilliant.
