### ISSUE TITLE
Bug: Default Hotkeys added, even when removed

### ISSUE THREAD

**Issue by chrisgrieser** [AlexBieg/obsidian-better-command-palette#10]
Some hotkeys are wrong, As far as I can tell, the wrong hotkeys are all default hotkeys for the respective commands. I suspect that the plugin is somehow reading the default hotkeys and then the "actual" hotkeys and displaying them both, resulting in the faulty display.

<img width="1125" alt="Screenshot 2022-01-28 15 05 05" src="https://user-images.githubusercontent.com/73286100/151562402-1497851b-0677-4a9c-a613-eb90c2aa88c5.png">
<img width="1077" alt="Screenshot 2022-01-28 14 54 50" src="https://user-images.githubusercontent.com/73286100/151562443-7aa067a9-629e-4082-8674-5e93e6528249.png">
<img width="1026" alt="Screenshot 2022-01-28 15 18 16" src="https://user-images.githubusercontent.com/73286100/151562535-df2e86ab-c094-4f5b-abbc-63789cdd8a5f.png">

**Comment by AlexBieg** [comment]
Should be fixed in master now
