### ISSUE TITLE
Pinned Commands ordered backwards

### ISSUE THREAD

**Issue by Khoding** [AlexBieg/obsidian-better-command-palette#22]
I just started using the plugin, it's nice overall, but there's one issue: my pinned commands in the built-in command palette are ordered backwards in this one.

Usually:
![Usually](https://i.imgur.com/6nn1dEn.png)

Now:
![Now](https://i.imgur.com/yruXUtI.png)

I guess I could just reorder them myself but I figured it wasn't implemented like that on purpose.

**Comment by AlexBieg** [comment]
Ah yup, that is not intended. Should be an easy fix. I'll push out a fix in a little bit.

**Comment by AlexBieg** [comment]
@Khoding Alrighty that should be fixed in 0.6.2. You should just need to update the plugin. Thanks for using it!
