### ISSUE TITLE
Toggle for switching between Obsidian's and Apple specific keyboard icons

### ISSUE THREAD

**Issue by Cutuchiqueno** [AlexBieg/obsidian-better-command-palette#28]
I like the plug-in so much that I entirely replaced Obsidians native command palette. I, however, find it very irritating, that the command palette now shows me Apple key icons for my shortcuts. I never used Apple, using Linux at home and Windows at work, thus, I do not even know how the icons/keys match to my keyboard. Especially for shortcuts I rarely use or that I just configured the shortcut icons in the command palette therefor do not really help me.

Could you add a toggle to the configuration to use Obsidians default icons or the Apple icons.

Thx.

**Comment by AlexBieg** [comment]
@Cutuchiqueno Just released 0.9.0. That adds in OS detection and a setting to force a hotkey style. One note that might affect you. I've changed the hotkey modifier used to create files from `Meta` (Mac: Cmd, Windows: Win) to `Mod` (Mac: Cmd, Windows: Ctrl). When initially developing, I thought `Meta` was Ctrl in windows, so I used it. For our purposes `Mod` is a more semantically correct key to use. If it becomes an issue I can develop something to let people change that, but for now I think it is a better default.
