### ISSUE TITLE
FR: Enable CSS Styling by Separating Plugin Name and Command Name

### ISSUE THREAD

**Issue by chrisgrieser** [AlexBieg/obsidian-better-command-palette#3]
splitting them into separate css classes allows to apply styling them like this:
<img width="1028" alt="Screenshot 2022-01-26 17 35 37" src="https://user-images.githubusercontent.com/73286100/151205987-20479027-5fc0-4f15-8962-32be6e0f628c.png">

but as the Better Command Palette right now puts both, plugin name and command name into one element/class, this kind of styling cannot be applied.

Ideally, the same css class names as with the original command palette should be used, so any the better command palette will inherit the styling any theme already applies to the normal command palette.
<img width="720" alt="Screenshot 2022-01-26 17 39 02" src="https://user-images.githubusercontent.com/73286100/151206738-42cbf65a-be60-478b-8f99-87a7aa857639.png">

**Comment by AlexBieg** [comment]
Yeah, that seems like a totally reasonable request. I'll add it to the queue.

Disclaimer: I'm employed full time so this only gets attention after work. If you need/want this feature ASAP I'm happy to review a PR 😄 Otherwise I'll get to it as soon as I can.
