### ISSUE TITLE
Display the shortcuts in the modal

### ISSUE THREAD

**Issue by Khoding** [AlexBieg/obsidian-better-command-palette#33]
This idea would mostly be for people with ADHD, but being able to see which shortcut we set (# for tags, / for files, etc) in the command modal somewhere would be very useful and appreciated.

**Comment by AlexBieg** [comment]
Yeah, that seems totally reasonable. I can add those to the instructions. I'll put it in the queue 😄

**Comment by AlexBieg** [comment]
I finally got this out. Sorry for the delay. Thank you very much for your patience 😄

**Comment by Khoding** [comment]
Nice to see a few updates coming 😄 thanks for adding this, it's very useful
