### ISSUE TITLE
[Feature Request] Customisable Key functions

### ISSUE THREAD

**Issue by Signynt** [AlexBieg/obsidian-better-command-palette#35]
It would be great to be able to customise which keys have which functions while using the palette. I usually use `Cmd` to open a file in a new pane with the Quick Switcher, and I'd like to be able to use the same key to do this with this plugin! (so `Cmd + Enter` to open in new pane)

**Comment by ryanjamurphy** [comment]
Came here to say something similar: the Better Command Palette switches the use of <kbd>cmd/ctrl</kbd> and <kbd>shift</kbd> from the core Command Palette, making it very counterintuitive to learn the hotkeys (and making switching between them a pain).

## Default command palette:
![Screen Shot 2022-02-16 at 12 01 21 PM](https://user-images.githubusercontent.com/3618647/154299195-0495adf6-89d9-4a94-bf05-733437dd28e5.png)

## Better command palette:
![Screen Shot 2022-02-16 at 12 01 30 PM](https://user-images.githubusercontent.com/3618647/154299206-cecab28c-8df3-4cbb-b122-062109a697f3.png)
 
It would be great to be able to switch it back!

**Comment by AlexBieg** [comment]
Thanks for checking out the plugin! That does make sense. I'll put it in the queue. It will likely be a bit of time before I can get to this due to work taking up a lot of my free time. Feel free to make a PR if you feel so inclined otherwise I'll get to this ASAP

**Comment by AlexBieg** [comment]
@ryanjamurphy @Signynt Alrighty, this feature just went out! A setting now switches file creation vs opening in a new pane between the `cmd` and `shift` keys. This should now allow you to use the same modifier keys as the normal quick switcher. Closing this ticket. Feel free to reopen if I missed anything.
