### ISSUE TITLE
[Bug] Native File Completer Formatting Broken with BCP Enabled

### ISSUE THREAD

**Issue by iamrecursion** [AlexBieg/obsidian-better-command-palette#41]
With "Better Command Palette" installed and active, the obsidian-native file completion popup has its formatting broken when highlighting the matching text. It seems to miss out any spaces in the bolded portion of the text, but I have no idea why this might be happening. See below for screenshots.

Note that this _does not_ happen in the standard open dialog, just the autocomplete that shows when you type `[[`.

As far as I can tell this was introduced with version 0.11.1.

#### Without Better Command Palette Enabled

<img width="581" alt="image" src="https://user-images.githubusercontent.com/5780639/154784818-683bcd3a-fd5d-4496-b565-234c5baa588c.png">

#### With Better Command Palette Enabled

<img width="573" alt="image" src="https://user-images.githubusercontent.com/5780639/154784854-bc327ae9-4ec4-4f3c-8cd5-ebb8fbdc47a1.png">

**Comment by AlexBieg** [comment]
Oops yup, I did not scope my suggestion item styles correctly. This has just been fixed in 0.11.4. Should be available for download in a few minutes.

**Comment by iamrecursion** [comment]
This is indeed fixed! Thank you very much!
