### ISSUE TITLE
[BUG] Cannot use `/` to search files

### ISSUE THREAD

**Issue by Quorafind** [AlexBieg/obsidian-better-command-palette#45]
![image](https://user-images.githubusercontent.com/13215013/156278173-d4ad8cb8-7b96-42b7-82d8-a8d725174713.png)

**Comment by AlexBieg** [comment]
@Quorafind Can you provide reproduction steps? I'm not able to reproduce this on my machine

**Comment by Rubecks** [comment]
I just installed this, and while I can search files with `/, it gives me the a.map error too, and I can't see the files on the root folder. But it finds files on the subfolders.

Installing it on the help vault, it works just fine.

I don't know how to reproduce this.

**Comment by Rubecks** [comment]
Ok, I found a way to replicate the a.map error. Just make a new note, and give an alias starting with a uppercase letter.

```
---
aliases: "Test"
---
```

**Comment by AlexBieg** [comment]
This should be fixed now! Updating the plugin to 0.11.5 should solve your issues
