### ISSUE TITLE
BUG: Built In Quick Switcher does not work properly

### ISSUE THREAD

**Issue by AtlcatlQ** [AlexBieg/obsidian-better-command-palette#64]
Thanks for the plugin I use it instead of the native command palette, and I think you could improve it even more!

now I'm having troubles using the hotkey to open a file in another pane. The command palette is just closed when I try to use the hotkey, instead of opening the note in a new pane.

**Comment by LilaRest** [comment]
Same problem for me. Have you found a solution @AtlcatlQ ?

Is this great project still maintained @AlexBieg ?

**Comment by LilaRest** [comment]
@AtlcatlQ I've just opened a PR (#91) that fixes this problem. You can install it using [BRAT](https://github.com/TfTHacker/obsidian42-brat).
Enjoy !

**Comment by AtlcatlQ** [comment]
> @AtlcatlQ I've just opened a PR (#91) that fixes this problem. You can install it using [BRAT](https://github.com/TfTHacker/obsidian42-brat). Enjoy !

Thanks, I don't know how to use brat, but thank you
