### ISSUE TITLE
No seperater between Collection name and command name

### ISSUE THREAD

**Issue by LintaoAmons** [AlexBieg/obsidian-better-command-palette#68]
Right now, when I search command, it shows commands like `OutlineShow outline pane`, But it should be render like `Outline - Show outline pane` or `Outline | Show outline pane`. The seperater char is missing.

- Example
![image](https://user-images.githubusercontent.com/95092244/179341762-64ec2f71-1206-4cf9-89c6-49ec23caec6e.png)

## Temp Fix
Thanks to [brimwats](https://github.com/brimwats), this could be fixed by adding the following into snippet.

```css
.suggestion-prefix:after {
  content: ": ";
}
```

**Comment by gapmiss** [comment]
Same issue here.

**Comment by chumido98** [comment]
Same. Please fix

**Comment by brimwats** [comment]
same: a comparision of BCP and CP:

![image](https://user-images.githubusercontent.com/73113656/180909381-51d9cf64-72c6-48c1-b826-1d2831d4fb99.png)
![image](https://user-images.githubusercontent.com/73113656/180909389-8d32fa96-3c03-4158-9b27-029d601e652c.png)

**Comment by sinewave** [comment]
Adding my +1 to this bug fix as it really kills the usability of this plugin to the point where I've switched back to the default.

Has anyone found a suitable alternative / fix - seems like this plugin may be abandoned 😞

**Comment by brimwats** [comment]
> Adding my +1 to this bug fix as it really kills the usability of this plugin to the point where I've switched back to the default.
> 
> Has anyone found a suitable alternative / fix - seems like this plugin may be abandoned 😞

yeah

this snippet

.suggestion-prefix:after {
    content: ": ";
}

**Comment by setu4993** [comment]
@brimwats : Nice fix! Would you be open to submitting a PR for the same to this repo? Not sure it's getting maintained, but would be good to add a fix for whenever @AlexBieg can look at it.

**Comment by brimwats** [comment]
I have no idea how to submit PRs!

**Comment by brimwats** [comment]
you're welcome to however! 🤗

**Comment by setu4993** [comment]
Just created #71 to fix this. Not sure when it'll be reviewed, but it's a simple fix. Thanks @brimwats!

**Comment by AlexBieg** [comment]
Sorry this took so long y'all! Grad school has been tiring, and doing extra coding can be tough. I appreciate your patience on this. I've put out a few new updates. This should be addressed now. Also included is a new setting to hide the plugin name entirely
