### ISSUE TITLE
Hide header text (better command pallete: commands)

### ISSUE THREAD

**Issue by tonyxiao** [AlexBieg/obsidian-better-command-palette#77]
Is there a way to hide this? Would find it much more visually appealing.
<img width="503" alt="image" src="https://user-images.githubusercontent.com/696842/199736912-5062e8bb-e574-4334-8dcc-9d21d71ce5ca.png">

**Comment by ChrisFiftyTwo** [comment]
Would like this as well. I am already well aware what plugin I am using and I gladly spread it far and wide to anyone who asks but I don't need to see it everytime I open the Command Palette (which is a lot).

**Comment by AlexBieg** [comment]
This was added in 0.15.0

**Comment by keyvanm** [comment]
@AlexBieg if the setting for this is "Show plugin name" when it is unselected, the name of the plugin for each command also gets hidden. For example, "Git: Pull" becomes just "Pull." With the option enabled, we can see the name of each command's plugin as a subheader (which is a much better UI than the original command palette), but this title text appears too. 

Can these two settings be separated?
