### ISSUE TITLE
FEATURE REQUEST: Slash command support

### ISSUE THREAD

**Issue by JaySpencer1234** [AlexBieg/obsidian-better-command-palette#79]
As great as the base slash command plugin is, I'd like to hide some of the commands that I never use. It would be great if it could use the same hide list as this plugin, so I'm requesting it here!

**Comment by AlexBieg** [comment]
Unfortunately, there isn't a way for this plugin to affect how a core plugin works. It would be nice to hide commands from the slash command. The only solution I can think of would be to recreate the slash plugin (similar to how this recreates the command palette) and add that extra functionality. That's pretty far out of the scope of this plugin so I'm going to close the ticket out.
