### ISSUE TITLE
FR: Customize the Quick Switcher that should be triggered with File Search

### ISSUE THREAD

**Issue by chrisgrieser** [AlexBieg/obsidian-better-command-palette#9]
right now, it seems that basically the normal quick switcher is triggered. However, there are some alternative quick switchers, e.g. [another quick switcher](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher), and I assume people opting for a better command palette are also quite likely to use an alternative quick switcher too. Would it be possible for the Better Command Palette to add a setting to trigger an alternative quick switcher?

**Comment by AlexBieg** [comment]
@chrisgrieser Are you asking for the palette to automatically open Another Quick Switcher when `/` is typed? If so, I'm not sure I understand your use case. If you use another quick switcher, wouldn't going through this palette first be an extra keypress that doesn't do anything. I think a hotkey for the switcher would work better. For example:

BCP hotkey -> Type '\' -> Quick switcher opens
vs
Quick switcher hotkey -> Quickswitcher opens

Also, I should note the normal quick search is not actually triggered why you type `/`. It is a custom quick switcher similar to `Another Quick Switcher`. I intend to keep adding features to it, but for the moment it is still very similar to the normal quick switcher (minus recently switched files bubbling up to the top).

**Comment by chrisgrieser** [comment]
Ah, I see, I thought it was triggering the quick switcher. 

Yeah, then this issue is irrelevant!
